spring.datasource.url=${NEONDB_URL}
spring.datasource.username=${NEONDB_USERNAME}
spring.datasource.password=${NEONDB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
